# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Yahoo-Music-Ratings
version:      2.00
version_from: lib/Yahoo/Music/Ratings.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
